baseURL = "http://abijango.com"
languageCode = "en-us"
title = "Butterfly Dream"
theme = "pixyll"
author = "Naufal"


[params]
  twitter_username = "abijango"
  paginate = true

  # number of posts to show on index
  # default: 10
  # HomepagePosts = 5
