baseURL = "https://elastic-ptolemy-bcc3be.netlify.com"
languageCode = "en-us"
title = "Butterfly Dream"
theme = "pixyll"
author = "Naufal"
publishDir = "docs"


[params]
  twitter_username = "abijango"
  paginate = true

  # number of posts to show on index
  # default: 10
  # HomepagePosts = 5
